overrides:
  socket.io-parser: '>=4.2.3'
  ws: '>=8.18.0'
  tinymce: '>=7.0.0'
  esbuild: '>=0.25.0'
  parseuri: '>=0.0.6'
  glob: '>=10.5.0'

allowBuilds:
  esbuild: true
  '@parcel/watcher': true
  unrs-resolver: true
